version: '3.2'
services:
  postgres:
    image: postgres:16
    container_name: tgbot_book_db
    command: -p 5440
    expose:
      - 5440
    env_file:
      - .env
    volumes:
      - ./db/:/var/lib/postgresql/data


  bot:
    build:
      context: .
    env_file:
      - .env
    container_name: tgbot_book
    command: ["docker_commands/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - postgres
